# Generated by Django 4.2.5 on 2023-11-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('google_maps_location', models.URLField(max_length=255)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('max_participants', models.PositiveIntegerField()),
                ('total_hours', models.PositiveIntegerField()),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invite-only', 'Invite Only')], max_length=15)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.program'),
        ),
        migrations.AddField(
            model_name='event',
            name='skills_required',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skill'),
        ),
    ]
