# Generated by Django 4.2.5 on 2023-11-12 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='badge_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category_type', models.CharField(choices=[('interest', 'Interest'), ('skill', 'Skill')], default='interest', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='users.category')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='organization_profile/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='organization_profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateTimeField(auto_now_add=True)),
                ('date_unfollowed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.category')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='volunteer_profile/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='volunteer_profile/')),
                ('bio', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('experiences', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('headline', models.TextField(blank=True, max_length=80)),
                ('badges', models.ManyToManyField(blank=True, related_name='volunteers', to='users.badge')),
                ('following_organizations', models.ManyToManyField(related_name='volunteers_following_organizations', through='users.Relationship', to='users.organization')),
                ('following_volunteers', models.ManyToManyField(related_name='followed_by_volunteers', through='users.Relationship', to='users.volunteer')),
                ('interests', models.ManyToManyField(blank=True, related_name='interested_volunteers', to='users.interest')),
                ('skills', models.ManyToManyField(blank=True, related_name='volunteers', to='users.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to='users.volunteer', verbose_name='follower volunteer'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_organizations', to='users.organization', verbose_name='following organization'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to='users.volunteer', verbose_name='followed volunteer'),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='followers_volunteers',
            field=models.ManyToManyField(related_name='organizations_followed_by_volunteers', through='users.Relationship', to='users.volunteer'),
        ),
        migrations.AddField(
            model_name='organization',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_organizations', to='users.interest'),
        ),
        migrations.AddField(
            model_name='organization',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='required_by_organizations', to='users.skill'),
        ),
        migrations.AddField(
            model_name='organization',
            name='volunteers',
            field=models.ManyToManyField(related_name='organizations', through='users.OrganizationMembership', to='users.volunteer'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('from_volunteer', 'to_volunteer', 'to_organization')},
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('volunteer', 'organization', 'role'), name='unique_membership'),
        ),
    ]
