# Generated by Django 4.2.5 on 2023-11-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='encoded_interests_skills',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='encoded_data',
            field=models.JSONField(default=dict),
        ),
    ]
