# Generated by Django 4.2.5 on 2023-11-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='post.post'),
        ),
    ]
