# Generated by Django 4.2.5 on 2023-10-05 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='last_name',
        ),
    ]
