# Generated by Django 4.2.5 on 2023-10-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill_remove_volunteer_skills_volunteer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
