# Generated by Django 4.2.5 on 2023-11-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_city_organization_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='country',
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
