# Generated by Django 4.2.5 on 2023-10-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_volunteer_date_of_birth_volunteer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
